spring.application.name=tfg

gemini.api.key=${GEMINI_API_KEY}

# Conexión a la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/chessai_db
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate (El ORM de Spring)
# 'update' crea o actualiza las tablas automáticamente basándose en tus clases Java
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true