spring.application.name=tfg

ai.provider=gemini
gemini.api.key=${GEMINI_API_KEY}
ollama.api.url=http://localhost:11434/api/generate
ollama.model=gemma4:e4b

# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/chessai_db
spring.datasource.username=postgres
spring.datasource.password=root

# Hibernate
# 'update' creates or updates tables automatically from the Java entities.
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
